<?php
$this->headTitle('Create Project');

$form = $this->form;
$form->prepare();
?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Projects</h1>
    </div>

    <div class="span6">
        <a href="<?php echo $this->url('project/create'); ?>" class="button mini pull-right">New Project</a>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>

    <div class="span12 page-content">
        <?php echo $this->form()->openTag($form->setAttribute('class', 'horizontal')); ?>
            <div class="control-group">
                <?php echo $this->formLabel($form->get('name')->setLabelAttributes(array(
                    'class' => 'control-label'
                ))); ?>
                <div class="controls">
                    <?php
                        echo $this->formText($form->get('name'));
                        echo $this->formElementErrors($form->get('name'), array(
                            'class' => 'error'
                        ));
                    ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $this->formLabel($form->get('description')->setLabelAttributes(array(
                    'class' => 'control-label'
                ))); ?>
                <div class="controls">
                    <?php
                        echo $this->formTextarea($form->get('description'));
                        echo $this->formElementErrors($form->get('description'), array(
                            'class' => 'error'
                        ));
                    ?>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <?php echo $this->formSubmit($form->get('save')); ?>
                    <a href="<?php echo $this->url('project/overview'); ?>">Cancel</a>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>