<?php $this->headTitle('Delete Project'); ?>

<div id="menu-tabs" class="container">
    <?php echo $this->navigation('navigation/main')->menu()->escapeLabels(false); ?>
</div>

<div class="main-content container">
    <div class="alert-box">
        <p>
            Are you sure you want to delete the project "<?php echo $this->project->getName(); ?>"?
        </p>

        <div class="form-actions">
            <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formSubmit($form->get('yes')->setAttribute('class', 'btn btn-danger')); ?>
            <?php echo $this->formSubmit($form->get('no')->setAttribute('class', 'btn')); ?>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>