<?php $this->headTitle('Delete Project'); ?>

<div class="main-content container">
    <div class="row">
        <div class="span6">
            <div class="alert-box">
                <p>
                    Are you sure you want to delete the project "<?php echo $this->project->getName(); ?>"?
                </p>

                <div class="form-actions">
                    <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->formSubmit($form->get('yes')->setAttribute('class', 'btn btn-danger')); ?>
                    <?php echo $this->formSubmit($form->get('no')->setAttribute('class', 'btn')); ?>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>