<?php $this->headTitle('Projects'); ?>

<p><a href="<?php echo $this->url('project/create'); ?>">New Project</a></p>

<?php if (count($this->projects)) { ?>
    <ul>
        <?php foreach ($this->projects as $project) { ?>
            <li>
                <h2>
                    <a href="<?php echo $this->url('project/view', array('id' => $project->getId())); ?>">
                        <?php echo $project->getName(); ?>
                    </a>
                </h2>

                <p><?php echo $project->getDescription(); ?></p>

                <ul>
                    <?php if ($this->userAccess('project_update')) { ?>
                    <li><a href="<?php echo $this->url('project/update', array('id' => $project->getId())); ?>">Update</a></li>
                    <?php } ?>
                    <?php if ($this->userAccess('project_delete')) { ?>
                    <li><a href="<?php echo $this->url('project/delete', array('id' => $project->getId())); ?>">Remove</a></li>
                    <?php } ?>
                </ul>
            </li>
        <?php } ?>
    </ul>
<?php } else { ?>
    <p>There are no projects yet, would you like to create one?</p>
<?php } ?>

<p><a href="<?php echo $this->url('project/create'); ?>">New Project</a></p>