<?php $this->headTitle('Projects'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Projects</h1>
    </div>

    <div class="span6">
        <a href="<?php echo $this->url('project/create'); ?>" class="button mini pull-right">New Project</a>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>

    <div class="span12 page-content">

        <?php if (count($this->projects)) { ?>
            <ul class="data-list">
                <?php foreach ($this->projects as $project) { ?>
                    <li>
                        <h2>
                            <a href="<?php echo $this->url('project/view', array('id' => $project->getId())); ?>">
                                <?php echo $project->getName(); ?>
                            </a>
                        </h2>

                        <p><?php echo $project->getDescription(); ?></p>

                        <ul class="actions">
                            <li><a href="<?php echo $this->url('project/view', array('id' => $project->getId())); ?>" class="button">View</a></li>
                            <?php if ($this->userAccess('project_update')) { ?>
                                <li><a href="<?php echo $this->url('project/update', array('id' => $project->getId())); ?>" class="button">Update</a></li>
                            <?php } ?>
                            <?php if ($this->userAccess('project_delete')) { ?>
                                <li><a href="<?php echo $this->url('project/delete', array('id' => $project->getId())); ?>" class="button negative">Remove</a></li>
                            <?php } ?>
                        </ul>
                    </li>
                <?php } ?>
            </ul>
        <?php } else { ?>
            <div class="alert">
                <strong>Oh oh</strong>
                <p>There are no projects yet, would you like to <a href="<?php echo $this->url('project/create'); ?>">create one</a>?</p>
            </div>
        <?php } ?>
    </div>
</div>
