<?php $this->headTitle('Project ' . $this->project->getName()); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Project <?php echo $this->project->getName(); ?></h1>
    </div>

    <div class="span6">
        <div class="pull-right">
            <a href="<?php echo $this->url('project/update', array(
                'id' => $this->project->getId(),
            )); ?>" class="button mini">Update</a>
            <a href="<?php echo $this->url('project/delete', array(
                'id' => $this->project->getId(),
            )); ?>" class="button mini negative">Delete</a>
        </div>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>
</div>

<div class="grid12 page-content">
    <?php if (!$this->repositories) { ?>
        <div class="span12">
            <h2>Repositories</h2>

            <div class="alert">
                <strong>Oh oh</strong>
                <p>There are no repositories yet, would you like to <a href="<?php echo $this->url('scm/create', array(
                    'project' => $this->project->getId(),
                )); ?>">create one</a>?</p>
            </div>
        </div>
    <?php } else { ?>
        <div class="span6">
            <h2>Repositories</h2>
        </div>

        <div class="span6">
            <div class="pull-right">
                <a href="<?php echo $this->url('scm/create', array(
                    'project' => $this->project->getId(),
                )); ?>" class="button mini">Create</a>
            </div>
        </div>

        <div class="span12">
            <ul class="data-list">
                <?php foreach ($this->repositories as $repository) { ?>
                <li>
                    <h2>
                        <a href="<?php echo $this->url('scm/view/tree', array('id' => $repository->getId())); ?>">
                            <?php echo $repository->getName(); ?>
                        </a>
                    </h2>

                    <p><?php echo $repository->getDescription(); ?></p>

                    <ul class="actions">
                        <li><a href="<?php echo $this->url('scm/view/tree', array('id' => $repository->getId())); ?>" class="button">View</a></li>
                        <?php if ($this->userAccess('repository_update')) { ?>
                            <li><a href="<?php echo $this->url('scm/update', array('id' => $repository->getId())); ?>" class="button">Update</a></li>
                        <?php } ?>
                        <?php if ($this->userAccess('repository_delete')) { ?>
                            <li><a href="<?php echo $this->url('scm/delete', array('id' => $repository->getId())); ?>" class="button negative">Remove</a></li>
                        <?php } ?>
                    </ul>
                </li>
                <?php } ?>
            </ul>
        </div>
    <?php } ?>
</div>
