<?php

$this->headTitle('Project ' . $this->project->getName());

echo '<h2>' . $this->project->getName() . '</h2>';

echo '<ul>';
echo '<li><a href="' . $this->url('project/update', array(
    'id' => $this->project->getId()
    )) . '">Update</a></li>';
echo '</ul>';

echo '<h3>Repositories</h3>';

echo '<ul>';
echo '<li><a href="' . $this->url('scm/create', array(
    'project' => $this->project->getId()
)) . '">Create</a></li>';
echo '</ul>';

if (!$this->repositories) {
    echo '<p>No repositories yet.</p>';
} else {
    echo '<ul>';
    foreach ($this->repositories as $repository) {
        echo '<li>';
        if ($repository->getType() == 'git') {
            echo '<h4><a href="' . $this->url('scm/view/tree', array('id' => $repository->getId())) . '">' . $repository->getName() . '</a></h4>';
        } else {
            echo '<h4>' . $repository->getName() . '</h4>';
        }
        echo '<p>' . $repository->getDescription() . '</p>';
        echo '<ul>';
        if ($this->userAccess('repository_update')) {
            echo '<li><a href="' . $this->url('scm/update', array('id' => $repository->getId())) . '">Update</a></li>';
        }
        if ($this->userAccess('repository_delete')) {
            echo '<li><a href="' . $this->url('scm/delete', array('id' => $repository->getId())) . '">Remove</a></li>';
        }
        echo '</ul>';
        echo '</li>';
    }
    echo '</ul>';
}
