<?php $this->headTitle('Delete SSH Key'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>SSH Keys</h1>
    </div>

    <div class="span6">
        <a href="<?php echo $this->url('ssh/create'); ?>" class="button mini pull-right">New Key</a>
    </div>
</div>

<div class="grid12 page-content">
    <div class="span3">
        <div class="boxed-group">
            <h3><?php echo $this->userDisplayName(); ?></h3>

            <div class="boxed-group-inner">
				<ul class="section-list">
					<li><a href="<?php echo $this->url('settings/profile'); ?>">Profile</a></li>
					<li class="selected"><a href="<?php echo $this->url('ssh/overview'); ?>">SSH Keys</a></li>
				</ul>
			</div>
        </div>
    </div>

    <div class="span9">
        <div class="boxed-group">
            <h3>SSH Keys</h3>
            <div class="boxed-group-inner content">
				<p>
					Are you sure you want to delete the SSH key "<?php echo $this->sshKey->getName(); ?>"?
				</p>

				<?php echo $this->form()->openTag($form); ?>
				<?php echo $this->formSubmit($form->get('yes')); ?>
				<a href="<?php echo $this->url('ssh/overview'); ?>">No</a>
				<?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

