<?php $this->headTitle('SSH Keys'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>SSH Keys</h1>
    </div>

    <div class="span6">
        <div class="pull-right">
            <a href="<?php echo $this->url('ssh/create'); ?>" class="button mini">New Key</a>
        </div>
    </div>
</div>

<div class="grid12 page-content">
    <div class="span3">
        <div class="boxed-group">
            <h3><?php echo $this->userDisplayName(); ?></h3>

            <div class="boxed-group-inner">
				<ul class="section-list">
					<li><a href="<?php echo $this->url('settings/profile'); ?>">Profile</a></li>
					<li class="selected"><a href="<?php echo $this->url('ssh/overview'); ?>">SSH Keys</a></li>
				</ul>
			</div>
        </div>
    </div>

    <div class="span9">
        <div class="boxed-group">
            <h3>SSH Keys</h3>
			<?php if (count($keys)) { ?>
				<div class="boxed-group-inner">
					<ul class="data-list">
						<?php foreach ($keys as $sshKey) { ?>
							<li>
								<?php echo $sshKey->getName(); ?>

								<ul class="actions">
									<li><a href="<?php echo $this->url('ssh/delete', array('id' => $sshKey->getId())); ?>" class="button negative mini">Remove</a></li>
								</ul>
							</li>
						<?php } ?>
					</ul>
				</div>
			<?php } else { ?>
				<div class="boxed-group-inner content">
					<p>You don't have any SSH keys yet, would you like to add one?</p>
				</div>
			<?php } ?>
            </div>
        </div>
    </div>
</div>
