<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->headMeta()->setCharset('utf-8'); ?>
        <?php echo $this->headTitle('Collaboratory')->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php
        echo $this->headScript()
            ->prependFile('http://code.jquery.com/jquery-1.8.2.min.js');

        echo $this->inlineScript();
        ?>
    </head>
    <body>

        <?php echo $this->content; ?>

    </body>
</html>
