<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Collaboratory')->setSeparator(' - ')->setAutoEscape(false);

        echo $this->headMeta()->setCharset('utf-8');

        echo $this->headLink()
            ->appendAlternate(array(
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/images/favicon.ico'
            ))
            ->offsetSetStylesheet(0, $this->basePath() . '/css/reset.css')
            ->offsetSetStylesheet(1, $this->basePath() . '/css/960_24_col.css')
            //->offsetSetStylesheet(2, $this->basePath() . '/css/debug.css')
            ->offsetSetStylesheet(10, $this->basePath() . '/css/layout.css')
            ->offsetSetStylesheet(11, $this->basePath() . '/css/layout-header.css')
            ->offsetSetStylesheet(12, $this->basePath() . '/css/layout-menu-tabs.css')
            ->offsetSetStylesheet(13, $this->basePath() . '/css/layout-content-tabs.css')
            ->offsetSetStylesheet(14, $this->basePath() . '/css/layout-alerts.css')
            ->offsetSetStylesheet(15, $this->basePath() . '/css/layout-forms.css')
            ->offsetSetStylesheet(16, $this->basePath() . '/css/layout-tips.css');

        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js');
        ?>

    </head>
    <body>

        <div id="header">
            <div class="container_24">
                <div class="grid_24">
                    <h1><a href="<?php echo $this->url('dashboard'); ?>">Collaboratory</a></h1>

                    <div id="toolbox">
                        <a href="<?php echo $this->url('user/profile'); ?>"><?php echo $this->userAvatar(); ?></a>
                        <a href="<?php echo $this->url('user/profile'); ?>"><?php echo $this->userDisplayName(); ?></a>
                        |
                        <a href="<?php echo $this->url('user/logout'); ?>">Logout</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container_24">
            <?php echo $this->content; ?>
        </div>

        <div id="footer">
            <div class="container_24">
                <div class="grid_24">
                    Copyright &copy; 2012 nextphp
                </div>
            </div>
        </div>

        <?php echo $this->inlineScript() ?>

    </body>
</html>
