<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->headMeta()->setCharset('utf-8'); ?>
        <?php echo $this->headTitle('Collaboratory')->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php
        echo $this->headScript()
            ->prependFile('http://code.jquery.com/jquery-1.8.2.min.js');

        echo $this->inlineScript();
        ?>
    </head>
    <body>

        <h1><a href="<?php echo $this->url('dashboard'); ?>">Collaboratory</a></h1>

        <ul>
            <li><?php echo $this->userAvatar(); ?> <?php echo $this->userDisplayName(); ?></li>
            <li><a href="<?php echo $this->url('user/profile'); ?>">Account</a></li>
            <li><a href="<?php echo $this->url('user/logout'); ?>">Logout</a></li>
        </ul>

        <hr />

        <?php echo $this->navigation('navigation/main')->menu()->escapeLabels(false); ?>

        <hr />

        <?php echo $this->content; ?>

    </body>
</html>
