<?php

$this->headTitle('Create Team');

$form = $this->form;
$form->prepare();

?>

<div id="menu-tabs" class="grid_24">
    <ul>
        <li><a href="<?php echo $this->url('dashboard'); ?>">News Feed</a></li>
        <li><a href="<?php echo $this->url('issueOverview'); ?>">Issues <span class="counter">0</span></a></li>
        <li><a href="<?php echo $this->url('projectOverview'); ?>">Projects</a></li>
        <li><a href="<?php echo $this->url('teamOverview'); ?>" class="selected">Teams</a></li>
    </ul>
</div>

<?php echo $this->form()->openTag($form); ?>
    <div class="main-content grid_11">
        <dl>
            <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
            <dd>
                <?php echo $this->formText($form->get('name')); ?>
                <?php echo $this->formElementErrors($form->get('name')); ?>
            </dd>

            <dt><?php echo $this->formLabel($form->get('description')); ?></dt>
            <dd>
                <?php echo $this->formTextarea($form->get('description')); ?>
                <?php echo $this->formElementErrors($form->get('description')); ?>
            </dd>
        </dl>
    </div>

    <hr class="grid_24" />

    <div class="grid_24 tar">
        <?php echo $this->formSubmit($form->get('save')->setAttribute('class', 'button positive')); ?>
    </div>

<?php echo $this->form()->closeTag(); ?>