<?php $this->headTitle('Projects'); ?>

<div id="menu-tabs" class="grid_24">
    <ul>
        <li><a href="<?php echo $this->url('dashboard'); ?>">News Feed</a></li>
        <li><a href="<?php echo $this->url('issueOverview'); ?>">Issues <span class="counter">0</span></a></li>
        <li><a href="<?php echo $this->url('projectOverview'); ?>" class="selected">Projects</a></li>
        <li><a href="<?php echo $this->url('teamOverview'); ?>">Teams</a></li>
    </ul>
</div>

<div class="main-content grid_13">
    <?php if (count($this->projects)) { ?>
    <ul class="collection">
        <?php foreach ($this->projects as $project) { ?>
        <li>
            <h3><a href="<?php echo $this->url('projectUpdate', array(
                'id' => $project->getId()
            )); ?>"><?php echo $project->getName(); ?></a></h3>
            <p><?php echo $project->getDescription(); ?></p>
            <ul class="actions">
                <li><a href="<?php echo $this->url('projectDelete', array(
                    'id' => $project->getId()
                )); ?>" class="button negative">Remove</a></li>
            </ul>
        </li>
        <?php } ?>
    </ul>
    <?php } else { ?>
    <p>There are no projects yet, would you like to create one?</p>
    <?php } ?>

    <div class="tar">
        <a href="<?php echo $this->url('projectCreate'); ?>" class="button">New Project</a>
    </div>
</div>

<div class="main-content grid_10 push_1">
    <div class="tip">
        <h3>Owners</h3>

        <p>You cannot remove the owners team. People in that team have full access rights.</p>
    </div>
</div>