<?php $this->headTitle('Delete Repository'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Repositories</h1>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>

    <div class="span12 page-content">
        <p>
            Are you sure you want to delete the repository "<?php echo $this->repository->getName(); ?>"?
        </p>

        <?php echo $this->form()->openTag($this->form); ?>
        <?php echo $this->formSubmit($this->form->get('yes')->setAttribute('class', 'negative')); ?>
        <a href="<?php echo $this->url('project/view', array(
            'id' => $this->repository->getProject()->getId(),
        )); ?>" class="button">No</a>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
