<?php $this->headTitle('Issues'); ?>

<p><a href="<?php echo $this->url('issue/create'); ?>">New Issue</a></p>

<hr />

<p>
    <label>
        Assigned to
        <select>
            <option value="">Anyone</option>
            <option value="">Walter Tamboer</option>
        </select>
    </label>
</p>

<p>
    <label>
        Status
        <select>
            <option value="">All</option>
            <option value="">New</option>
            <option value="">Feedback</option>
            <option value="">Confirmed</option>
            <option value="">Assigned</option>
            <option value="">Resolved</option>
            <option value="">Closed</option>
        </select>
    </label>

</p>

<p>
    <label>
        Label
        <select>
            <option value="">All</option>
            <option value="">Label A</option>
            <option value="">Label B</option>
            <option value="">Label C</option>
            <option value="">Label D</option>
        </select>
    </label>

</p>

<p>
    <label>
        Priority
        <select>
            <option value="">All</option>
            <option value="">None</option>
            <option value="">Low</option>
            <option value="">Normal</option>
            <option value="">High</option>
            <option value="">Immediate</option>
        </select>
    </label>

</p>

<p>
    <button>Apply</button>
</p>

<p>No issues found.</p>