<?php $this->headTitle('Profile'); ?>

<div class="main-content grid_6">
    <div class="box">
        <a class="title" href="<?php echo $this->url('accountProfile'); ?>">
            <img width="20" height="20" src="https://secure.gravatar.com/avatar/c6b462cc4df153f563355d5d6edc1618?s=140&amp;d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png">
            WalterTamboer
        </a>
        <ul>
            <li><a href="<?php echo $this->url('accountProfile'); ?>">Profile</a></li>
            <li><a href="<?php echo $this->url('accountLogin'); ?>">Login</a></li>
            <li><a href="<?php echo $this->url('accountSsh'); ?>">SSH Keys</a></li>
        </ul>
    </div>
</div>

<div class="main-content grid_17 push_1">
    <div class="box">
        <h3 class="title">Profile</h3>
    </div>
</div>