<?php $this->headTitle('Add SSH Key'); ?>

<div class="main-content grid_6">
    <div class="box">
        <a class="title" href="<?php echo $this->url('account/profile'); ?>">
            <img width="20" height="20" src="https://secure.gravatar.com/avatar/c6b462cc4df153f563355d5d6edc1618?s=140&amp;d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png">
            WalterTamboer
        </a>
        <ul class="menu">
            <li><a href="<?php echo $this->url('account/profile'); ?>">Profile</a></li>
            <li><a href="<?php echo $this->url('account/login'); ?>">Login</a></li>
            <li class="selected"><a href="<?php echo $this->url('account/ssh'); ?>">SSH Keys</a></li>
        </ul>
    </div>
</div>

<?php echo $this->form()->openTag($form); ?>
<div class="main-content grid_17 push_1">
    <div class="box">
        <h3 class="title">
            Add SSH Key
        </h3>
        <div class="content">
            <dl>
                <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
                <dd>
                    <?php echo $this->formText($form->get('name')); ?>
                    <?php echo $this->formElementErrors($form->get('name')); ?>
                </dd>

                <dt><?php echo $this->formLabel($form->get('content')); ?></dt>
                <dd>
                    <?php echo $this->formTextarea($form->get('content')); ?>
                    <?php echo $this->formElementErrors($form->get('content')); ?>
                </dd>
            </dl>
        </div>
    </div>

    <div class="tar">
        <?php echo $this->formSubmit($form->get('save')->setAttribute('class', 'button positive')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>