<?php $this->headTitle('Sign In'); ?>

<div class="dialog inline login">
    <h1 class="dialog-title">Collaboratory</h1>

    <p class="dialog-description">Sign in using your Collaboratory account:</p>

    <?php echo $this->form()->openTag($form->setAttribute('class', 'horizontal')); ?>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('identity')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php echo $this->formText($form->get('identity')); ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('credential')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php echo $this->formPassword($form->get('credential')); ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->formSubmit($form->get('login')); ?>
            </div>
        </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
