<?php $this->headTitle('Sign In'); ?>
<?php $this->headLink()->offsetSetStylesheet(100, $this->basePath() . '/user/css/login.css'); ?>

<div class="account-container">
    <div class="content clearfix">
        <?php echo $this->form()->openTag($form->setAttribute('class', 'form-signin')); ?>

        <h1>Collaboratory</h1>

        <div class="login-fields">
            <p>Sign in using your Collaboratory account:</p>

            <div class="field">
                <label for="identity">Username:</label>
                <input type="text" id="identity" name="identity" value="" placeholder="Email address" class="login identity-field" />
            </div>

            <div class="field">
                <label for="credential">Password:</label>
                <input type="password" id="credential" name="credential" value="" placeholder="Password" class="login credential-field"/>
            </div>
        </div>

        <div class="login-actions">
            <button class="button btn btn-warning btn-large">Sign In</button>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
