<?php $this->headTitle('Profile'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Account</h1>
    </div>

    <div class="span6">
        <div class="pull-right">
        </div>
    </div>
</div>

<div class="grid12 page-content">
    <div class="span3">
        <div class="boxed-group">
            <h3><?php echo $this->userDisplayName(); ?></h3>

            <ul class="section-list">
                <li><a href="<?php echo $this->url('settings/profile'); ?>">Profile</a></li>
                <li><a href="<?php echo $this->url('ssh/overview'); ?>">SSH Keys</a></li>
            </ul>
        </div>
    </div>

    <div class="span9">
        <div class="boxed-group">
            <h3>Public Profile</h3>

            <div class="boxed-group-inner">
                <?php
                echo $this->form()->openTag($form);
                echo $this->formRow($form->get('displayName'));
                echo $this->formSubmit($form->get('save'));
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
