<?php $this->headTitle('Profile'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Profile</h1>
    </div>

    <div class="span6">
        <div class="pull-right">
        </div>
    </div>
</div>

<div class="grid12 page-content">
    <div class="span3">
        <div class="boxed-group">
            <h3><?php echo $this->userDisplayName(); ?></h3>

            <div class="boxed-group-inner">
				<ul class="section-list">
					<li class="selected"><a href="<?php echo $this->url('settings/profile'); ?>">Profile</a></li>
					<li><a href="<?php echo $this->url('ssh/overview'); ?>">SSH Keys</a></li>
				</ul>
			</div>
        </div>
    </div>

    <div class="span9">
        <div class="boxed-group">
            <h3>Public Profile</h3>

            <div class="boxed-group-inner content">
				<?php echo $this->form()->openTag($form->setAttribute('class', 'horizontal')); ?>
					<div class="control-group">
						<?php echo $this->formLabel($form->get('displayName')->setLabelAttributes(array(
							'class' => 'control-label'
						))); ?>
						<div class="controls">
							<?php
								echo $this->formText($form->get('displayName'));
								echo $this->formElementErrors($form->get('displayName'), array(
									'class' => 'error'
								));
							?>
						</div>
					</div>
					<div class="control-group">
						<div class="controls">
							<?php echo $this->formSubmit($form->get('save')); ?>
						</div>
					</div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
