<?php $this->headTitle('Sign In'); ?>

<div class="dialog inline small">
    <h1 class="dialog-title">Collaboratory</h1>

    <p class="dialog-description">Did you forget your password? Request a new one:</p>

    <?php echo $this->form()->openTag($form->setAttribute('class', 'horizontal')); ?>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('identity')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php echo $this->formText($form->get('identity')); ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->formSubmit($form->get('request')); ?>
                <a href="<?php echo $this->url('user/login'); ?>"> or login</a>
            </div>
        </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
