<?php $this->headTitle('SSH Keys'); ?>

<div class="main-content grid_6">
    <div class="box">
        <a class="title" href="<?php echo $this->url('user/profile'); ?>">
            <?php echo $this->userAvatar(); ?>
            <?php echo $this->userDisplayName(); ?>
        </a>
        <ul class="menu">
            <li class="selected"><a href="<?php echo $this->url('user/profile'); ?>">Profile</a></li>
            <li><a href="<?php echo $this->url('user/ssh'); ?>">SSH Keys</a></li>
        </ul>
    </div>
</div>

<div class="main-content grid_17 push_1">
    <div class="box">
        <h3 class="title">
            SSH Keys

            <ul class="actions">
                <li><a href="" class="button">Add SSH Key</a></li>
            </ul>
        </h3>
        <div class="content">
            <ul>
                <li>
                    Computer 1
                    <ul class="actions">
                        <li><a href="" class="button negative">Remove</a></li>
                    </ul>
                </li>
                <li>
                    Computer 2
                    <ul class="actions">
                        <li><a href="" class="button negative">Remove</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>