<?php $this->headTitle('Install'); ?>

<div class="dialog">
	<h1 class="dialog-title">Installer</h1>

	<div class="dialog-content">
		<h2>Account</h2>

		<p>
			In order to log in, you need an account. Please create one here:
		</p>
        
        <?php echo $this->form()->openTag($this->form->setAttribute('class', 'horizontal')); ?>
            <div class="control-group">
                <?php echo $this->formLabel($form->get('identity')->setLabelAttributes(array(
                    'class' => 'control-label'
                ))); ?>
                <div class="controls">
                    <?php
                        echo $this->formText($form->get('identity'));
                        echo $this->formElementErrors($form->get('identity'), array(
                            'class' => 'error'
                        ));
                    ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $this->formLabel($form->get('credential')->setLabelAttributes(array(
                    'class' => 'control-label'
                ))); ?>
                <div class="controls">
                    <?php
                        echo $this->formPassword($form->get('credential'));
                        echo $this->formElementErrors($form->get('credential'), array(
                            'class' => 'error'
                        ));
                    ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $this->formLabel($form->get('validation')->setLabelAttributes(array(
                    'class' => 'control-label'
                ))); ?>
                <div class="controls">
                    <?php
                        echo $this->formPassword($form->get('validation'));
                        echo $this->formElementErrors($form->get('validation'), array(
                            'class' => 'error'
                        ));
                    ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $this->formLabel($form->get('displayName')->setLabelAttributes(array(
                    'class' => 'control-label'
                ))); ?>
                <div class="controls">
                    <?php
                        echo $this->formText($form->get('displayName'));
                        echo $this->formElementErrors($form->get('displayName'), array(
                            'class' => 'error'
                        ));
                    ?>
                </div>
            </div>
        
            <div class="button-bar">
                <div class="pull-left"><a class="button" href="<?php echo $this->url('install/database'); ?>">Back</a></div>
                <div class="pull-right"><?php echo $this->formSubmit($form->get('save')); ?></div>
                <div class="clear"></div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
	</div>
</div>