<?php $this->headTitle('Install'); ?>

<div class="dialog">
	<h1 class="dialog-title">Installer</h1>

	<div class="dialog-content">
		<h2>Finish</h2>

		<p>
			You are about to finish the installation. Are the settings below correct?
		</p>

		<h3>Database</h3>

		<table class="settings-table">
			<tr>
				<td class="name">Host</td>
				<td class="value"><?php echo $this->database['host']; ?></td>
			</tr>
			<tr>
				<td class="name">Port</td>
				<td class="value"><?php echo $this->database['port']; ?></td>
			</tr>
			<tr>
				<td class="name">Username</td>
				<td class="value"><?php echo $this->database['username']; ?></td>
			</tr>
			<tr>
				<td class="name">Password</td>
				<td class="value"><?php echo $this->database['password']; ?></td>
			</tr>
			<tr>
				<td class="name">Database</td>
				<td class="value"><?php echo $this->database['dbname']; ?></td>
			</tr>
		</table>

		<h3>Account</h3>

		<table class="settings-table">
			<tr>
				<td class="name">E-mail address</td>
				<td class="value"><?php echo $this->account['identity']; ?></td>
			</tr>
			<tr>
				<td class="name">Password</td>
				<td class="value"><?php echo $this->account['credential']; ?></td>
			</tr>
			<tr>
				<td class="name">Display name</td>
				<td class="value"><?php echo $this->account['displayName']; ?></td>
			</tr>
		</table>
        
        <?php echo $this->form()->openTag($this->form); ?>
            <div class="button-bar">
                <div class="pull-left"><a class="button" href="<?php echo $this->url('install/account'); ?>">Back</a></div>
                <div class="pull-right"><?php echo $this->formSubmit($form->get('save')); ?></div>
                <div class="clear"></div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
	</div>
</div>