<?php $this->headTitle('Install'); ?>

<div class="dialog">
	<h1 class="dialog-title">Installer</h1>

	<div class="dialog-content">
		<h2>System</h2>
        
		<p>
			Welcome! You are about to install Collaboratory. Before we do so we have to make sure that all system settings are correct:
		</p>

		<table class="settings-table">
		<?php foreach ($this->systemSettings as $setting) { ?>
			<tr class="<?php echo $setting->isValid() ? 'valid' : 'invalid'; ?>">
				<td class="name"><?php echo $setting->getName(); ?></td>
				<td class="value"><?php echo $setting->getMessage(); ?></td>
			</tr>
		<?php } ?>
		</table>

		<?php if ($this->canContinue) { ?>
		<div class="button-bar">
			<div class="pull-left"><a class="button" href="<?php echo $this->url('install'); ?>">Restart</a></div>
			<div class="pull-right"><a class="button" href="<?php echo $this->url('install/database'); ?>">Next</a></div>
            <div class="clear"></div>
		</div>
		<?php } ?>
	</div>
</div>