#!/bin/bash

RESULT="`/usr/bin/php -f /home/$USER/data/shell/collaboratory-shell.php \"$1\"`"

if [[ "$RESULT" =~ "git-upload-pack|git-receive-pack|git-upload-archive" ]]; then
    git shell -c "$RESULT"
else
    echo "$RESULT" >&2
fi
