#!/usr/bin/php
<?php

// Set the current timezone:
date_default_timezone_set('Europe/Amsterdam');

// The username that is active:
$username = $_SERVER['argv'][1];

// The directory of today's logs:
$logDirectory = '/home/' . $_SERVER['USER'] . '/logs/git/' . $username;
mkdir($logDirectory, 0777, true);

// The file to log to:
$logFile = $logDirectory . '/' . date('Y-m-d') . '.log';

// Open the log file:
$f = fopen($logFile, 'a+');

fwrite($f, 'Date: ' . date('Y-m-d H:i:s') . PHP_EOL);
fwrite($f, 'System user: ' . $_SERVER['USER'] . PHP_EOL);
fwrite($f, 'Local user: ' . $username . PHP_EOL);
fwrite($f, 'Parameters: ' . implode(' ', $_SERVER['argv']) . PHP_EOL);
fwrite($f, 'Connection: ' . $_SERVER['SSH_CONNECTION'] . PHP_EOL);
fwrite($f, 'Command: ' . $_SERVER['SSH_ORIGINAL_COMMAND'] . PHP_EOL);

if (preg_match("/^git-upload-pack|git-receive-pack|git-upload-archive /?(.*?)(?:\.git(\d)?)?$/i", $_SERVER['SSH_ORIGINAL_COMMAND'], $matches)) {
	fwrite($f, print_r($matches, true));
}

//git shell -c "$PARSED1 $PARSED2"

fclose($f);
