<?php

$this->headTitle('Create Snippet');

$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('syntax'));
echo $this->formRow($form->get('content'));
echo $this->formSubmit($form->get('save'));
echo '<a href="' . $this->url('snippet/overview') . '">Cancel</a>';
echo $this->form()->closeTag();
