<?php $this->headTitle('Delete Snippet'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Delete Snippet</h1>
    </div>

    <div class="span6">
        <a href="<?php echo $this->url('snippet/create'); ?>" class="button mini pull-right">New Snippet</a>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>

    <div class="span12 page-content">
        <p>
            Are you sure you want to delete the snippet "<?php echo $this->snippet->getName(); ?>"?
        </p>

        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formSubmit($form->get('yes')->setAttribute('class', 'button positive')); ?>
        <a href="<?php echo $this->url('snippet/overview'); ?>">No</a>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>