<?php $this->headTitle('Snippets'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Snippets</h1>
    </div>

    <div class="span6">
        <a href="<?php echo $this->url('snippet/create'); ?>" class="button mini pull-right">New Snippet</a>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>

    <?php if (count($snippets)) { ?>
        <div class="span12 page-content">
            <ul class="data-list">
                <?php foreach ($snippets as $snippet) { ?>
                    <li>
                        <h3 class="title"><a href="<?php
                            echo $this->url('snippet/update', array(
                                'id' => $snippet->getId()
                            ));
                        ?>"><?php echo $snippet->getName(); ?></a></h3>
                        <div class="description"><?php echo $snippet->getDescription(); ?></div>
                        <ul class="actions">
                            <li><a href="<?php
                                echo $this->url('snippet/delete', array(
                                    'id' => $snippet->getId()
                                ));
                             ?>" class="button negative">Remove</a></li>
                        </ul>
                    </li>
                <?php } ?>
            </ul>
        </div>
    <?php } else { ?>
        <div class="span12 page-content">
            <div class="alert">
                <strong>Oh oh</strong>
                <div>There are no snippets yet, would you like to <a href="<?php echo $this->url('snippet/create'); ?>">create one</a>?</div>
            </div>
        </div>
    <?php } ?>
</div>