<?php $this->headTitle('Snippets'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Snippets</h1>
    </div>

    <div class="span6">
        <a href="<?php echo $this->url('snippet/create'); ?>" class="button pull-right">New Snippet</a>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>

<?php if (count($snippets)) { ?>
    <ul>
        <?php foreach ($snippets as $snippet) { ?>
            <li>
                <h3><a href="<?php
        echo $this->url('snippet/update', array(
            'id' => $snippet->getId()
        ));
        ?>"><?php echo $snippet->getName(); ?></a></h3>
                <p><?php echo $snippet->getDescription(); ?></p>
                <ul>
                    <li><a href="<?php
        echo $this->url('snippet/delete', array(
            'id' => $snippet->getId()
        ));
            ?>">Remove</a></li>
                </ul>
            </li>
    <?php } ?>
    </ul>
<?php } else { ?>
    <div class="span12">
        <div class="alert info">
            <strong>Oh oh</strong>
            <p>There are no snippets yet, would you like to create one?</p>
        </div>
    </div>
<?php } ?>
</div>