<?php $this->headTitle('Snippets'); ?>

<p><a href="<?php echo $this->url('snippet/create'); ?>" class="button">New Snippet</a></p>

<?php if (count($snippets)) { ?>
    <ul>
        <?php foreach ($snippets as $snippet) { ?>
            <li>
                <h3><a href="<?php
        echo $this->url('snippet/update', array(
            'id' => $snippet->getId()
        ));
        ?>"><?php echo $snippet->getName(); ?></a></h3>
                <p><?php echo $snippet->getDescription(); ?></p>
                <ul>
                    <li><a href="<?php
        echo $this->url('snippet/delete', array(
            'id' => $snippet->getId()
        ));
            ?>" class="button negative">Remove</a></li>
                </ul>
            </li>
    <?php } ?>
    </ul>
<?php } else { ?>
    <p>There are no snippets yet, would you like to create one?</p>
<?php } ?>


<p><a href="<?php echo $this->url('snippet/create'); ?>" class="button">New Snippet</a></p>