<?php
$this->headTitle('New Account');

$form = $this->form;
$form->prepare();
?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Accounts</h1>
    </div>

    <div class="span6">
        <?php if ($this->userAccess('user_create')) { ?>
            <a href="<?php echo $this->url('account/create'); ?>" class="button mini pull-right">New Account</a>
        <?php } ?>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>
</div>

<div class="grid12 page-content">
    <?php echo $this->form()->openTag($form->setAttributes(array(
        'class' => 'horizontal',
    ))); ?>
    <div class="span12">
        <div class="control-group">
            <?php echo $this->formLabel($form->get('identity')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php
                echo $this->formText($form->get('identity'));
                echo $this->formElementErrors($form->get('identity'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('credential')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php
                echo $this->formPassword($form->get('credential'));
                echo $this->formElementErrors($form->get('credential'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('validation')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php
                echo $this->formPassword($form->get('validation'));
                echo $this->formElementErrors($form->get('validation'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('displayName')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php
                echo $this->formText($form->get('displayName'));
                echo $this->formElementErrors($form->get('displayName'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>
    </div>
    <div class="span6">
        <div class="control-group">
            <div class="controls">
                <?php
                echo $this->formAutocomplete($form->get('teams'), array(
                    'url' => $this->basePath() . '/api/rest/teams',
                    'key' => 'id',
                    'lbl' => 'name',
                ));
                echo $this->formElementErrors($form->get('teams'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->formSubmit($form->get('save')); ?>
                <a href="<?php echo $this->url('account/overview'); ?>">Cancel</a>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>