<?php

$this->headTitle('Create User');

$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('identity'));
echo $this->formRow($form->get('credential'));
echo $this->formRow($form->get('validation'));
echo $this->formRow($form->get('displayName'));
echo '<hr />';
echo $this->formCollection($form->get('teams'));
echo '<hr />';
echo $this->formSubmit($form->get('save'));
echo '<a href="' . $this->url('account/overview') . '">Cancel</a>';
echo $this->form()->closeTag();
