<?php $this->headTitle('Accounts'); ?>

<p><a href="<?php echo $this->url('account/create'); ?>">New User</a></p>

<?php if (count($accounts)) { ?>
    <ul>
        <?php foreach ($accounts as $account) { ?>
            <li>
                <h2>
                    <a href="<?php echo $this->url('account/update', array('id' => $account->getId())); ?>">
                        <?php echo $this->userDisplayName($account); ?>
                    </a>
                </h2>

                <p>
                    <?php echo $account->getIdentity(); ?>
                </p>

                <?php if ($account->getId() != $this->userIdentity()->getId()) { ?>
                    <ul>
                        <li><a href="<?php echo $this->url('account/delete', array('id' => $account->getId())); ?>">Remove</a></li>
                    </ul>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
<?php } else { ?>
    <p>There are no users yet, would you like to create one?</p>
<?php } ?>

<p><a href="<?php echo $this->url('account/create'); ?>">New User</a></p>