<?php $this->headTitle('Accounts'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Accounts</h1>
    </div>

    <div class="span6">
        <?php if ($this->userAccess('user_create')) { ?>
            <a href="<?php echo $this->url('account/create'); ?>" class="button mini pull-right">New Account</a>
        <?php } ?>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>
</div>

<div class="grid12 page-content">
    <div class="span12">
<?php if (count($accounts)) { ?>
    <ul class="data-list">
        <?php foreach ($accounts as $account) { ?>
            <li>
                <h2>
                    <?php if ($this->userAccess('user_update')) { ?>
                        <a href="<?php echo $this->url('account/update', array('id' => $account->getId())); ?>">
                    <?php } ?>
                        <?php echo $this->userDisplayName($account); ?>
                    <?php if ($this->userAccess('user_update')) { ?>
                        </a>
                    <?php } ?>
                </h2>

                <div>
                    <?php echo $account->getIdentity(); ?>
                </div>

                <?php if ($this->userAccess('user_delete') && $account->getId() != $this->userIdentity()->getId()) { ?>
                    <ul class="actions">
                        <li><a href="<?php echo $this->url('account/delete', array('id' => $account->getId())); ?>" class="button negative">Remove</a></li>
                    </ul>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
<?php } else { ?>
    <p>There are no users yet, would you like to create one?</p>
<?php } ?>

    </div>
</div>