<?php
$this->headTitle('Update User');

$form = $this->form;
$form->prepare();
?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Account</h1>
    </div>

    <div class="span6">
        <div class="pull-right">
            <a href="<?php
                echo $this->url('account/create'); ?>" class="button mini">New Account</a>
        </div>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>
</div>

<div class="grid12 page-content">
    <div class="span12">
        <?php
        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('identity'));
        echo $this->formRow($form->get('credential'));
        echo $this->formRow($form->get('validation'));
        echo $this->formRow($form->get('displayName'));
        echo '<hr />';
        echo $this->formCollection($form->get('teams'));
        echo '<hr />';
        echo $this->formSubmit($form->get('save'));
        echo '<a href="' . $this->url('account/overview') . '">Cancel</a>';
        echo $this->form()->closeTag();
        ?>
    </div>
</div>