<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php

        echo $this->headTitle('Collaboratory')->setSeparator(' - ')->setAutoEscape(false);

        echo $this->headMeta()->setCharset('utf-8');

        echo $this->headLink()
            ->appendAlternate(array(
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/images/favicon.ico'
            ))
            ->appendStylesheet($this->basePath() . '/css/screen.css');

        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js');
        ?>

    </head>
    <body>

        <div id="header">
            <div class="container">
                <h1><a href="<?php echo $this->url('dashboard'); ?>">Collaboratory</a></h1>

                <div id="toolbox">
                    <a href="<?php echo $this->url('account'); ?>"><?php echo $this->gravatar('w.tamboer@polderknowledge.nl')->setImgSize(16); ?></a>
                    <a href="<?php echo $this->url('account'); ?>">Walter Tamboer</a>

                    <a href="<?php echo $this->url('projectCreate'); ?>">Create Project</a>
                </div>

                <div class="clear"></div>
            </div>
        </div>

<?php echo $this->content; ?>

<?php echo $this->inlineScript() ?>

    </body>
</html>
