<?php
$this->headTitle('Create Team');
$this->headScript()->appendFile($this->basePath() . '/js/team.js');

$form = $this->form;
$form->prepare();

?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Teams</h1>
    </div>

    <div class="span6">
        <?php if ($this->canCreateTeam()) { ?>
            <a href="<?php echo $this->url('team/create'); ?>" class="button mini pull-right">New Team</a>
        <?php } ?>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>
</div>

<div class="grid12 page-content">
    <?php echo $this->form()->openTag($form->setAttributes(array(
        'class' => 'horizontal',
    ))); ?>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('name')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php
                echo $this->formText($form->get('name'));
                echo $this->formElementErrors($form->get('name'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('description')->setLabelAttributes(array(
                'class' => 'control-label'
            ))); ?>
            <div class="controls">
                <?php
                echo $this->formTextarea($form->get('description'));
                echo $this->formElementErrors($form->get('description'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>

        <hr />

        <div class="control-group">
            <div class="controls">
                <?php
                echo $this->formCollection($form->get('members'));
                echo $this->formElementErrors($form->get('members'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <?php
                echo $this->formCollection($form->get('projects'));
                echo $this->formElementErrors($form->get('projects'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>

        <hr />

        <div class="control-group">
            <div class="controls">
                <?php
                echo $this->formMultiCheckbox($form->get('permissions'));
                echo $this->formElementErrors($form->get('permissions'), array(
                    'class' => 'error'
                ));
                ?>
            </div>
        </div>

        <hr />

        <div class="control-group">
            <div class="controls">
                <?php echo $this->formSubmit($form->get('save')); ?>
                <a href="<?php echo $this->url('team/overview'); ?>">Cancel</a>
            </div>
        </div>
    <?php echo $this->form()->closeTag(); ?>
</div>