<?php

$this->headTitle('Create Team');
$this->headScript()->appendFile($this->basePath() . '/js/team.js');

$form = $this->form;
$form->prepare();

$teamFieldset = $form->get('team');

?>

<div id="menu-tabs" class="grid_24">
    <?php echo $this->navigation('navigation/main')->menu()->escapeLabels(false); ?>
</div>

<?php echo $this->form()->openTag($form->setAttribute('autocomplete', 'off')); ?>
    <div class="main-content grid_11">
        <dl>
            <dt><?php echo $this->formLabel($teamFieldset->get('name')); ?></dt>
            <dd>
                <?php echo $this->formText($teamFieldset->get('name')); ?>
                <?php echo $this->formElementErrors($teamFieldset->get('name')); ?>
                <div class="example" style="margin-top: 10px;">(e.g. Programmers, Concept Artists, Managers)</div>
            </dd>
        </dl>
    </div>

    <div class="main-content grid_11 push_2">
        <dl>
            <dt><?php echo $this->formLabel($teamFieldset->get('description')); ?></dt>
            <dd>
                <?php echo $this->formTextarea($teamFieldset->get('description')); ?>
                <?php echo $this->formElementErrors($teamFieldset->get('description')); ?>
            </dd>
        </dl>
    </div>

    <hr class="grid_24" />

    <div class="grid_24 permissions">
        <h2>Permissions</h2>

        <?php echo $this->formMultiCheckbox($teamFieldset->get('permissions')); ?>
    </div>

    <hr class="grid_24" />

    <div class="grid_11" id="team-members-list">
        <h2>Members</h2>

        <ul class="small-list">
            <?php foreach ($this->teamMembers as $member) { ?>
            <li>
                <input type="hidden" name="team[members][][id]" value="<?php echo $member->getId(); ?>" />
                <?php echo $this->userDisplayName($member); ?>
                <a href="" class="delete">(remove)</a>
            </li>
            <?php } ?>
        </ul>

        <div class="form-add-box">
            <input type="text" name="" value="" id="team-members-ajax" />
            <button>Add</button>

            <div class="clearfix"></div>
        </div>
    </div>

    <div class="grid_11 push_2" id="team-projects-list">
        <h2>Projects</h2>

        <ul class="small-list">
            <?php foreach ($this->teamProjects as $project) { ?>
            <li>
                <input type="hidden" name="team[projects][][id]" value="<?php echo $project->getId(); ?>" />
                <?php echo $project->getName(); ?>
                <a href="" class="delete">(remove)</a>
            </li>
            <?php } ?>
        </ul>

        <div class="form-add-box">
            <input type="text" name="" value="" id="team-projects-ajax" />
            <button onclick="return false;">Add</button>

            <div class="clearfix"></div>
        </div>
    </div>

    <hr class="grid_24" />

    <div class="grid_24 tar">
        <button type="submit" class="positive">Save</button>
    </div>

<?php echo $this->form()->closeTag(); ?>