<?php $this->headTitle('Teams'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Teams</h1>
    </div>

    <div class="span6">
        <?php if ($this->canCreateTeam()) { ?>
            <a href="<?php echo $this->url('team/create'); ?>" class="button mini pull-right">New Team</a>
        <?php } ?>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>
</div>

<div class="grid12 page-content">
    <div class="span12">
        <?php if (count($teams)) { ?>
            <ul class="data-list">
                <?php foreach ($teams as $team) { ?>
                    <li>
                        <h2>
                            <?php if ($this->canUpdateTeam($team)) { ?>
                                <a href="<?php echo $this->url('team/update', array('id' => $team->getId())); ?>">
                                <?php } ?>
                                <?php echo $team->getName(); ?>
                                <?php if ($this->canUpdateTeam($team)) { ?>
                                </a>
                            <?php } ?>
                        </h2>

                        <div><?php echo $team->getDescription(); ?></div>

                        <?php if ($this->canRemoveTeam($team) || $this->canUpdateTeam($team)) { ?>
                            <ul class="actions">
                                <?php if ($this->canUpdateTeam($team)) { ?>
                                    <li><a href="<?php echo $this->url('team/update', array('id' => $team->getId())); ?>" class="button">Update</a></li>
                                <?php } ?>
                                <?php if ($this->canRemoveTeam($team)) { ?>
                                    <li><a href="<?php echo $this->url('team/delete', array('id' => $team->getId())); ?>" class="button negative">Remove</a></li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
        <?php } else { ?>
            <div class="alert">
                <strong>Oh oh</strong>
                <div>There are no teams yet, would you like to <a href="<?php echo $this->url('team/create'); ?>">create one</a>?</div>
            </div>
        <?php } ?>
    </div>
</div>