<?php
$this->headTitle('Update Team');
$this->headScript()->appendFile($this->basePath() . '/js/team.js');

$form = $this->form;
$form->prepare();

$teamFieldset = $form->get('team');

echo $this->form()->openTag($form->setAttribute('autocomplete', 'off'));
echo $this->formRow($teamFieldset->get('name'));
echo $this->formRow($teamFieldset->get('description'));
echo '<hr />';
echo $this->formCollection($teamFieldset->get('members'));
if (!$this->team->isRoot()) {
    echo $this->formCollection($teamFieldset->get('projects'));
    echo '<hr />';
    echo $this->formMultiCheckbox($teamFieldset->get('permissions'));
}
echo '<hr />';
echo $this->formSubmit($teamFieldset->get('save'));
echo '<a href="' . $this->url('team/overview') . '">Cancel</a>';
echo $this->form()->closeTag();
