<?php $this->headTitle('Delete Team'); ?>

<div id="menu-tabs" class="grid_24">
    <?php echo $this->navigation('navigation/main')->menu()->escapeLabels(false); ?>
</div>

<div class="grid_10 push_7 tac">
    <div class="alert-box">
        <p>
            Are you sure you want to delete the team "<?php echo $this->team->getName(); ?>"?
        </p>
    </div>

    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formSubmit($form->get('yes')->setAttribute('class', 'button positive')); ?>
    <?php echo $this->formSubmit($form->get('no')->setAttribute('class', 'button negative')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>