<?php $this->headTitle('Delete Team'); ?>

<div id="menu-tabs" class="grid_24">
    <ul>
        <li><a href="<?php echo $this->url('dashboard'); ?>">News Feed</a></li>
        <li><a href="<?php echo $this->url('issueOverview'); ?>">Issues <span class="counter">0</span></a></li>
        <li><a href="<?php echo $this->url('projectOverview'); ?>">Projects</a></li>
        <li><a href="<?php echo $this->url('teamOverview'); ?>" class="selected">Teams</a></li>
    </ul>
</div>

<div class="grid_24">
    <div class="alert-box">
        <p>
            Are you sure you want to delete the team "<?php echo $team->getName(); ?>"?
        </p>
    </div>
    <div>

        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formSubmit($form->get('yes')->setAttribute('class', 'button positive')); ?>
        <?php echo $this->formSubmit($form->get('no')->setAttribute('class', 'button negative')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>