<?php $this->headTitle('Teams'); ?>

<div id="menu-tabs" class="grid_24">
    <ul>
        <li><a href="<?php echo $this->url('dashboard'); ?>">News Feed</a></li>
        <li><a href="<?php echo $this->url('issueOverview'); ?>">Issues <span class="counter">0</span></a></li>
        <li><a href="<?php echo $this->url('projectOverview'); ?>">Projects</a></li>
        <li><a href="<?php echo $this->url('teamOverview'); ?>" class="selected">Teams</a></li>
    </ul>
</div>

<div class="main-content grid_13">
    <?php if (count($teams)) { ?>
    <ul class="collection">
        <?php foreach ($teams as $team) { ?>
        <li>
            <h3><a href="<?php echo $this->url('teamUpdate', array(
                'id' => $team->getId()
            )); ?>"><?php echo $team->getName(); ?></a></h3>
            <p><?php echo $team->getDescription(); ?></p>
            <ul class="actions">
                <li><a href="<?php echo $this->url('teamDelete', array(
                    'id' => $team->getId()
                )); ?>" class="button negative">Remove</a></li>
            </ul>
        </li>
        <?php } ?>
    </ul>
    <?php } else { ?>
    <p>There are no teams yet, would you like to create one?</p>
    <?php } ?>

    <div class="tar">
        <a href="<?php echo $this->url('teamCreate'); ?>" class="button">New Team</a>
    </div>
</div>

<div class="main-content grid_10 push_1">
    <div class="tip">
        <h3>Owners</h3>

        <p>You cannot remove the owners team. People in that team have full access rights.</p>
    </div>
</div>