<?php

$this->headTitle('Update Team');

$form = $this->form;
$form->prepare();

$teamFieldset = $form->get('team');

?>

<div id="menu-tabs" class="grid_24">
    <ul>
        <li><a href="<?php echo $this->url('dashboard'); ?>">News Feed</a></li>
        <li><a href="<?php echo $this->url('issueOverview'); ?>">Issues <span class="counter">0</span></a></li>
        <li><a href="<?php echo $this->url('projectOverview'); ?>">Projects</a></li>
        <li><a href="<?php echo $this->url('teamOverview'); ?>" class="selected">Teams</a></li>
    </ul>
</div>

<?php echo $this->form()->openTag($form); ?>
    <div class="main-content grid_11">
        <dl>
            <dt><?php echo $this->formLabel($teamFieldset->get('name')); ?></dt>
            <dd>
                <?php echo $this->formText($teamFieldset->get('name')); ?>
                <div class="example" style="margin-top: 10px;">(e.g. Programmers, Concept Artists, Managers)</div>
            </dd>
        </dl>
    </div>

    <div class="main-content grid_11 push_2">
        <dl>
            <dt><?php echo $this->formLabel($teamFieldset->get('description')); ?></dt>
            <dd><?php echo $this->formTextarea($teamFieldset->get('description')); ?></dd>
        </dl>
    </div>

    <hr class="grid_24" />

    <div class="grid_24 permissions">
        <h2>Permissions</h2>

        <?php echo $this->formMultiCheckbox($teamFieldset->get('permissions')); ?>
    </div>

    <hr class="grid_24" />

    <div class="grid_11">
        <h2>Members</h2>

        <ul class="small-list">
            <li><?php echo $this->gravatar('walter.tamboer@live.com')->setImgSize(20); ?> Walter Tamboer <a href="" class="delete">(remove)</a></li>
            <li><?php echo $this->gravatar('walter.tamboer@live.com')->setImgSize(20); ?> John Doe <a href="" class="delete">(remove)</a></li>
            <li><?php echo $this->gravatar('walter.tamboer@live.com')->setImgSize(20); ?> John Doe <a href="" class="delete">(remove)</a></li>
            <li><?php echo $this->gravatar('walter.tamboer@live.com')->setImgSize(20); ?> John Doe <a href="" class="delete">(remove)</a></li>
            <li><?php echo $this->gravatar('walter.tamboer@live.com')->setImgSize(20); ?> John Doe <a href="" class="delete">(remove)</a></li>
        </ul>

        <div class="form-add-box">
            <input type="text" name="" value="" />
            <button>Add</button>

            <div class="clearfix"></div>
        </div>
    </div>

    <div class="grid_11 push_2">
        <h2>Projects</h2>

        <ul class="small-list">
            <li>Project X <a href="" class="delete">(remove)</a></li>
            <li>Project Y <a href="" class="delete">(remove)</a></li>
            <li>Project Z <a href="" class="delete">(remove)</a></li>
        </ul>

        <div class="form-add-box">
            <input type="text" name="" value="" />
            <button onclick="return false;">Add</button>

            <div class="clearfix"></div>
        </div>
    </div>

    <hr class="grid_24" />

    <div class="action-bar grid_24">
        <button type="submit" class="positive">Save</button>
    </div>

<?php echo $this->form()->closeTag(); ?>