<?php $this->headTitle('News Feed'); ?>

<div id="menu-tabs" class="grid_24">
    <?php echo $this->navigation('navigation/main')->menu()->escapeLabels(false); ?>
</div>

<div class="main-content grid_13">
    <?php for ($i = 0; $i < 3; ++$i) { ?>
    <div class="alert project created">
        <div class="title">
            <a href="">Person A</a> <span>created project</span> <a href="">test</a>
            <time title="2012-07-29 19:59:42" datetime="2012-07-29T19:59:42Z">just now</time>
        </div>
    </div>
    <div class="alert branch created">
        <div class="title">
            <a href="">Person B</a> <span>created branch</span> <a href="">test</a>
            <time title="2012-07-29 19:59:42" datetime="2012-07-29T19:59:42Z">just now</time>
        </div>
    </div>
    <div class="alert branch deleted">
        <div class="title">
            <a href="">Person C</a> <span>deleted branch</span> <a href="">hotfix/123</a>
            <time title="2012-07-29 19:59:42" datetime="2012-07-29T19:59:42Z">just now</time>
        </div>
    </div>
    <div class="alert pushed">
        <time title="2012-07-29 19:59:42" datetime="2012-07-29T19:59:42Z">3 months ago</time>

        <div class="title">
            <a href="">Walter Tamboer</a> <span>pushed</span> to master at <a href="">project</a>
        </div>
        <div class="details">
            <a href="<?php echo $this->url(); ?>" class="avatar"><?php echo $this->gravatar('walter.tamboer@live.com')->setImgSize(32); ?></a>
            <div class="commits">
                <ul>
                    <li>
                        <code>
                            <a href="/pixelpolishers/resolver/commit/7df0c81b77ab1a511875cae15686cddc69091693">7df0c81</a>
                        </code>
                        <blockquote title="The initial commit." class="message">
                            The initial commit.
                        </blockquote>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <?php } ?>
</div>

<div class="main-content grid_10 push_1">
    <div class="tip">
        <h3>Timeboxing</h3>

        <p>Did you know you can manage the time you work on issues using Collaboratory?</p>
        <p><a href="">Find out more here!</a></p>
    </div>

    <div class="tip">
        <h3>Another Tip</h3>

        <p>Did you know you can manage the time you work on issues using Collaboratory?</p>
        <p><a href="">Find out more here!</a></p>
    </div>

    <div class="tip">
        <h3>Another Tip</h3>

        <p>Did you know you can manage the time you work on issues using Collaboratory?</p>
        <p><a href="">Find out more here!</a></p>
    </div>
</div>