<?php $this->headTitle('News Feed'); ?>

<div class="grid12 page-header">
    <div class="span12">
        <h1>News Feed</h1>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>
</div>

<div class="grid12 page-content">
    <div class="span12">
        <?php foreach ($this->applicationEvents as $event) { ?>
            <div class="news">
                <?php echo $this->renderApplicationEvent($event); ?>
            </div>
        <?php } ?>
    </div>
</div>
