<?php $this->headTitle('Calendar'); ?>

<div class="grid12 page-header">
    <div class="span6">
        <h1>Calendar</h1>
    </div>

    <nav class="span12 navbar">
        <?php echo $this->collabMenu('main'); ?>
    </nav>
</div>

<div class="grid12 page-content">
    <div class="span12">
        <?php echo $this->calendar(array(
            'year' => date('Y'),
            'month' => date('n'),
            'calendars' => $this->calendars,
        )); ?>
    </div>
</div>
